device:
  name: bramble
  build_id: UP1A.231105.001.B2
  prev_build_id: UP1A.231105.001
  platform_security_patch_level_override: 2023-12-01

platform:
  product_makefile: device/google/bramble/aosp_bramble.mk

includes:
  - common/gen5pixel.yml

filters:
  sepolicy_dirs:
    match:
      - device/google/redbull-sepolicy/system_ext/private
  files:
    match:
      - vendor/bin/gpu_counter_producer
      - system/etc/vintf/manifest/hwservicemanager.xml
      - system/etc/init/hwservicemanager.rc
      - system/etc/vintf/manifest/android.hidl.allocator@1.0-service.xml
      - system/etc/init/android.hidl.allocator@1.0-service.rc
      - system/bin/hw/android.hidl.allocator@1.0-service
      - system/lib64/libclcore_neon.bc
      - system_ext/priv-app/AccessibilityMenu/AccessibilityMenu.apk