platform:
  sepolicy_dirs:
    - device/google/gs201-sepolicy

includes:
  - pixel.yml

filters:
  dep_files:
    match:
      # external/android-nn-driver/Android.mk: error: "android.hardware.neuralnetworks@1.0-service-armnn (EXECUTABLES android-arm64) missing libOpenCL (SHARED_LIBRARIES android-arm64)"
      - vendor/lib/libOpenCL.so
      - vendor/lib64/libOpenCL.so

      - system_ext/framework/google-ril.jar

      - vendor/lib64/libgril_oem-google.so
      - system_ext/etc/permissions/google-ril.xml

      - product/etc/sysconfig/allowlist_com.shannon.imsservice.xml

      - system_ext/priv-app/grilservice/grilservice.apk
      - product/priv-app/CarrierServices/CarrierServices.apk